### ISSUE TITLE
Straightforward error - there is no check after setting ArrayList from Node, it crashes on NullPointerException

### ISSUE THREAD

**Issue by mrovnanik** [dataquest-dev/moqui-framework#21]
https://github.com/dataquest-dev/moqui-framework/blob/5c7448d20ee1b5f50c900c5c9154510f091369b9/framework/src/main/groovy/org/moqui/impl/entity/EntityFacadeImpl.groovy#L884-L885

fix in code, please. plus add a unit test that uses entity with no relationships set

**Comment by mrovnanik** [comment]
Beside that, why don't we use `relationships` variable on line 885, but instead use the same `getChildrenByName` method?

**Comment by Paurikova2** [comment]
This issue is solving in branch: relationship/no-check-after-setting-ArrauList-from-node
